/* Generated by PC Speaker Tracker */
/* Line time: 40 ms  |  Channels: 4 (mono mix: CH1 priority) */

#include <dos.h>

void spk_on(unsigned int freq) {
    unsigned int d = 1193182U / freq;
    outp(0x43, 0xB6);
    outp(0x42, d & 0xFF);
    outp(0x42, (d >> 8) & 0xFF);
    outp(0x61, inp(0x61) | 0x03);
}
void spk_off(void) { outp(0x61, inp(0x61) & ~0x03); }

/* Pattern P00 (73 rows) */
static const unsigned int pat0_freq[] = {
    65, 123, 0, 0, 0, 0, 0, 0, 65, 659, 494, 659, 494, 0, 0, 0, 0, 740, 622, 740, 622, 0, 784, 659, 784, 659, 0, 0, 0, 0, 740, 880, 740, 880, 740, 880, 0, 0, 0, 0, 65, 784, 659, 784, 659, 0, 0, 0, 65, 587, 740, 587, 740, 0, 784, 659, 784, 659, 0, 0, 0, 0, 659, 523, 659, 523, 659, 523, 659, 523, 659, 523, 65
};
#define PAT0_LEN 73

/* Song order (1 entries) */
static const int song_order[] = {0};
#define SONG_ORDER_LEN 1

/* Pattern data table */
typedef struct { const unsigned int *freq; int len; } Pattern;
static const Pattern patterns[] = {
    { pat0_freq, PAT0_LEN },
};

/* Play the full song */
void play_song(void) {
    int oi, ri;
    for (oi = 0; oi < SONG_ORDER_LEN; oi++) {
        const Pattern *p = &patterns[song_order[oi]];
        for (ri = 0; ri < p->len; ri++) {
            unsigned int f = p->freq[ri];
            if (f) { spk_on(f); } else { spk_off(); }
            delay(40);
        }
    }
    spk_off();
}
